### ISSUE TITLE
Lock acquisition is delayed for two tries on initial set of lock

### ISSUE THREAD

**Issue by jeremywadsack** [nickelser/suo#4]
If a lock key has never been set, [`Suo::Client::Base#acquire_lock` retries the acquisition](https://github.com/nickelser/suo/blob/af1c476f0875418bc48724b0ab54f82905f5bd2d/lib/suo/client/base.rb#L106) rather than returning the token:

```
      retry_with_timeout do
          val, cas = get

          if val.nil?
            initial_set
            next
          end

        ...
      end
```

The `next` in the code above is effectively equivalent to not having that line (because the next retry would pass to the code following which clears locks). Is it necessary to make that pass? It seems that it should `return token` here.

Because of this, Suo won't acquire a lock unless the retry count is 2 or more. So if I configure with `:acquisition_timeout` less than or equal to `: acquisition_delay`, even though [`@retry_count` gets the `ceil`](https://github.com/nickelser/suo/blob/af1c476f0875418bc48724b0ab54f82905f5bd2d/lib/suo/client/base.rb#L21) of the dividend, 1 try isn't enough to acquire a lock.

I'm happy to open a PR to change this, but I want to make sure I understand this correctly and I'm not missing something important.

**Comment by nickelser** [comment]
thank you again for your contribution!
